feat: create sidebar with widgets
dmytropihur/linkUp-Academy-ToDoApp pull request #3
Opened 2022-07-02 11:09 UTC by dmytropihur

2022-07-04 12:50 UTC, vovataras requested changes

2022-07-04 12:50 UTC, vovataras commented on src/App.tsx
> +    ]).then((values) => console.log(values));
Не розумію для чого так робити, якщо нам не треба чекати на виконання всіх запитів. По-перше, якщо вилетить помилка на якомусь віджеті, то всі інші які ще не виконувались, не будуть виконуватись (це через метод `all`), по-друге, не варто залишати `console.log` в готовому коді

2022-07-04 12:50 UTC, vovataras commented on src/constants/constants.ts
> +export const WEATHER_API_KEY = 'f60051ce4c436632e8957f7576eada33';
такі речі, як ключі треба тримати в файлі `.env`, а тут вже можна було б витягнути його з того файлу

2022-07-04 12:50 UTC, vovataras commented on src/store/dogImage/types.ts
> +};
типи повторюються, можна зробити тип, який буде в собі по замовчуванню вже мати статус і робити з ним об'єднання

2022-07-04 12:50 UTC, vovataras commented on src/utils/transformWeatherData.ts
> +  const weather = obj;
для чого так робити?

2022-07-04 12:50 UTC, vovataras commented on src/store/dogImage/slice.ts
> +          // eslint-disable-next-line max-len
для чого тут цей дісейбл?

2022-07-04 12:50 UTC, vovataras commented on src/store/bored/slice.ts
> +          // eslint-disable-next-line max-len
те саме

2022-07-04 12:50 UTC, vovataras commented on src/store/catFact/slice.ts
> +          // eslint-disable-next-line max-len
і тут

2022-07-04 12:50 UTC, vovataras commented on src/store/ipGeo/slice.ts
> +          // eslint-disable-next-line max-len
тут також

2022-07-04 12:56 UTC, dmytropihur commented on src/App.tsx
> +    ]).then((values) => console.log(values));
Зрозумів

2022-07-04 12:57 UTC, dmytropihur commented on src/constants/constants.ts
> +export const WEATHER_API_KEY = 'f60051ce4c436632e8957f7576eada33';
Знаю про .env, але на час перевірки вирішив залишити так, щоб тобі не приходилось зі своєї сторони нічого конфігурувати

2022-07-04 12:58 UTC, dmytropihur commented on src/store/dogImage/slice.ts
> +          // eslint-disable-next-line max-len
без нього вискакувала помилка через довжину строки

2022-07-04 13:01 UTC, dmytropihur commented on src/utils/transformWeatherData.ts
> +  const weather = obj;
Що саме? Наскільки розумію, дані з апішки приходять в величині kelvin, потрібно це трансформувати в цельсій

2022-07-04 13:02 UTC, dmytropihur commented on src/store/dogImage/types.ts
> +};
Добре

2022-07-04 13:04 UTC, vovataras commented on src/utils/transformWeatherData.ts
> +  const weather = obj;
для чого робити нову змінну? можна просто приймати параметр з назвою `weather` замість obj

2022-07-04 13:06 UTC, dmytropihur commented on src/utils/transformWeatherData.ts
> +  const weather = obj;
аа, ок, не подумав

2022-07-04 13:06 UTC, vovataras commented on src/store/dogImage/slice.ts
> +          // eslint-disable-next-line max-len
тут не довга стрічка, якщо відформатувати через прітієр, то все добре (в тих місцях, де залишив коментарі те саме, бо в одному файлі дійсно довга стрічка і там треба дісейбл)

2022-07-04 13:41 UTC, dmytropihur commented on src/store/bored/slice.ts
> +          // eslint-disable-next-line max-len
Поправив

2022-07-04 13:42 UTC, dmytropihur commented on src/store/catFact/slice.ts
> +          // eslint-disable-next-line max-len
Поправив

2022-07-04 13:42 UTC, dmytropihur commented on src/store/ipGeo/slice.ts
> +          // eslint-disable-next-line max-len
Поправив

2022-07-05 11:18 UTC, vovataras approved these changes

2022-07-05 11:18 UTC, vovataras commented on src/components/List/List.module.scss
> +    font-size: 60px !important;
старайся уникати `!important` і використовуй лише в крайніх випадках

2022-07-05 11:18 UTC, vovataras commented on src/utils/transformWeatherData.ts
> +  obj.main = {
при такому створенні треба було зробити новий об'єкт і тоді ми не будемо модифікувати попередній і функція буде чистою. Попередній коментар був до того, що `const weather = obj` було не потрібне, тому що так не робиться копія об'єкту, а робиться лише нове посилання на той ж самий об'єкт

2022-07-06 08:35 UTC, dmytropihur commented on src/utils/transformWeatherData.ts
> +  obj.main = {
поправив

2022-07-06 08:36 UTC, dmytropihur commented on src/components/List/List.module.scss
> +    font-size: 60px !important;
через те що MUI має свої класи, які перебивають мої, потрібно було використати, але знаю про те що бажано !important не використовувати

2022-07-06 08:36 UTC, merged